---
- hosts: mysql
  become: true
  remote_user: root
  tasks:
    - import_role:
        name: mysql
      tags:
        - mysql


- hosts: app
  become: true
  remote_user: root
  tasks:
    - import_role:
        name: rvm
      tags:
        - rvm

    - import_role:
        name: install-app
      tags:
        - install-app
