---
- hosts: db
  become: true
  remote_user: root
  tasks:
    - import_role:
        name: mysql
      tags:
        - mysql


- hosts: app
  become: true
  remote_user: root
  tasks:
    - import_role:
        name: rvm
      tags:
        - rvm

    - import_role:
        name: install-app
      tags:
        - install-app

- hosts: reverse-proxy
  become: true
  remote_user: root
  tasks:
    - import_role:
        name: firewalld
      tags:
        - firewalld

    - import_role:
        name: nginx
      tags:
        - nginx

    - import_role:
        name: nginx-vhost
      tags:
        - nginx-vhost
