---
- name: Open firewalld ports
  firewalld:
    port: "80/tcp"
    permanent: true
    state: enabled
    zone: public
  notify: Reload firewalld

- name: Add vhost configuration file
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/app.conf"
  notify: Reload nginx

- name: flush_handlers
  meta: flush_handlers

- name: Can I join host?
  become: false
  changed_when: false
  uri:
    url: "http://localhost"
  tags: smoke-test
